title: Recursive Learning
url: https://recursivelearning.app
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  clients:
    output: true
    permalink: /:collection/:name

# Default layouts
defaults:
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: "bhb"
    values:
      client: "bhb"
      layout: "chat"

# Production settings
production_url: "https://recursivelearning.app"
api_endpoint: "https://tixnmh1pe8.execute-api.us-east-2.amazonaws.com/prod/IntegralEd-Main"

# Development settings
development:
  api_endpoint: "http://127.0.0.1:4000/api"

# Include directories
include:
  - BHB
  - assets
  - _layouts
  - _includes

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CNAME
  - .DS_Store
  - "*.log"

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"
