title: Recursive Learning
description: >-
  Recursive Learning - Adaptive Learning Platform
baseurl: ""
url: "https://recursivelearning.app"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  clients:
    output: true
    permalink: /:collection/:path

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "chat"

# Include directories
include:
  - BHB
  - assets
  - _layouts
  - _includes

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CNAME
  - .DS_Store
  - "*.log"

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"

# Development settings
development:
  environment: development
  baseurl: ""
  url: "http://localhost:4000"
