title: "Recursive Learning"
baseurl: ""      # If deploying at domain root, keep empty
url: "https://recursivelearning.app"
markdown: kramdown
theme: minima

# API settings
api_endpoint: "https://tixnmh1pe8.execute-api.us-east-2.amazonaws.com/prod/IntegralEd-Main"

# Collections
collections:
  clients:
    output: true
    permalink: /clients/:path/

# Default layouts
defaults:
  - scope:
      path: "_clients"
      type: "clients"
    values:
      layout: "chat"

include:
  - _clients
  - assets
  - _layouts
  - _includes

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CNAME
  - .DS_Store
  - "*.log"
  - bhb     # Exclude standalone bhb directory

plugins:
  - jekyll-feed

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"
