# Jekyll configuration for Recursive Learning Frontend
# Updated: 2024-03-28 - Trigger clean build with new workflow

# Site settings
title: Recursive Learning
description: Context-aware learning platform
baseurl: ""
url: "https://recursivelearning.app"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  clients:
    output: true
    permalink: /clients/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "default"

# Include these files/folders
include:
  - _clients/**/*.html
  - _clients/**/static/**/*
  - assets
  - _layouts
  - _includes
  - "*.html"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - DEVELOPMENT.md

# Keep files during clean
keep_files:
  - .git
  - .gitignore
  - clients/**/static/**
  - assets/util-pages/**

# API settings
api_endpoint: "https://tixnmh1pe8.execute-api.us-east-2.amazonaws.com/prod/IntegralEd-Main"

# Default layouts for different file types
defaults:
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "chat"

# Files to include in build
include:
  - assets
  - _layouts
  - _includes
  - _clients/**/*.html
  - _clients/**/static/**/*

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CNAME
  - .DS_Store
  - "*.log"
  - _site
  - .jekyll-cache

# Keep files in _site
keep_files:
  - .nojekyll
  - CNAME
  - clients/**/static/**

# Plugins
plugins:
  - jekyll-seo-tag

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"
