title: "Recursive Learning"
baseurl: ""      # Keep empty for root domain
url: "https://recursivelearning.app"
markdown: kramdown
theme: minima

include:
  - clients
  - shared_jekyll
  - assets
  - "*.html"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"

plugins:
  - jekyll-feed

# Development settings
development:
  environment: development
  baseurl: ""
  url: "http://localhost:4000"
