# Jekyll configuration for Recursive Learning Frontend
# Updated: 2024-03-28 - Trigger clean build with new workflow

# Site settings
title: Recursive Learning
description: Context-aware learning platform
baseurl: ""
url: "https://recursivelearning.app"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  client_pages:
    output: true
    permalink: /:collection/:path/
    directory: _clients

# Defaults
defaults:
  - scope:
      path: ""
      type: "client_pages"
    values:
      layout: "chat"

# Include these files/folders
include:
  - assets/**/*
  - _layouts/**/*
  - _includes/**/*
  - _clients/**/*.md
  - _clients/**/assets/**/*
  - "*.html"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - DEVELOPMENT.md
  - CNAME
  - .DS_Store
  - "*.log"
  - _site
  - .jekyll-cache
  # Exclude client pages that aren't ready for deployment
  - _clients/bhb/pages/*.md
  # Add other client pages to exclude as needed

# Keep files during clean
keep_files:
  - .nojekyll
  - CNAME
  - assets/**/*

# API settings
api_endpoint: "https://tixnmh1pe8.execute-api.us-east-2.amazonaws.com/prod/IntegralEd-Main"

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"
