# Jekyll configuration for Recursive Learning
# This file configures the site's collections, defaults, and plugins

title: "Recursive Learning"
baseurl: ""      # If deploying at domain root, keep empty
url: "https://recursivelearning.app"
markdown: kramdown
theme: minima

# API settings
api_endpoint: "https://tixnmh1pe8.execute-api.us-east-2.amazonaws.com/prod/IntegralEd-Main"

# Collections configuration
collections:
  clients:
    output: true
    permalink: /clients/:path/
    layout: chat

# Default layouts for different file types
defaults:
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "chat"

# Files to include in build
include:
  - assets
  - _layouts
  - _includes

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CNAME
  - .DS_Store
  - "*.log"
  - _site
  - .jekyll-cache

# Keep files in _site
keep_files:
  - .nojekyll
  - CNAME

# Plugins
plugins:
  - jekyll-seo-tag

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"
