title: "Recursive Learning"
baseurl: ""      # If deploying at domain root, keep empty
url: "https://recursivelearning.app"
markdown: kramdown
theme: minima

include:
  - clients
  - shared_jekyll
  - assets

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"

plugins:
  - jekyll-feed
