name: Deploy Static Files

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: main
        force_orphan: true
        cname: recursivelearning.app
        commit_message: |
          Deploy static files to GitHub Pages
          
          Please verify:
          1. All static files are present
          2. All intended sites are accessible
          3. Test shared components if this is a feature update
        enable_jekyll: false
        disable_nojekyll: true
        keep_files: false

# API settings 