name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl "/clients"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
          cname: recursivelearning.app
          commit_message: "Deploy updates to GitHub Pages"
