name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler: 2.4.22
      - name: Install dependencies
        run: bundle install
      - name: Build site with Jekyll
        run: |
          pwd
          ls -la
          bundle exec jekyll build --trace
          ls -la _site/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          force_orphan: true
          cname: recursivelearning.app
          commit_message: "Deploy updates to GitHub Pages"
          enable_jekyll: false
